/**
 * Comprehensive error codes for workflow module operations
 * Each code has specific meaning for frontend consumption
 * Format: MODULE_OPERATION_RESULT
 */

// ============================================
// WORKFLOW OPERATION CODES
// ============================================

export enum WorkflowOperationCode {
  // Success codes
  WORKFLOW_CREATED = 'WORKFLOW_CREATED',
  WORKFLOW_UPDATED = 'WORKFLOW_UPDATED',
  WORKFLOW_DELETED = 'WORKFLOW_DELETED',
  WORKFLOWS_RETRIEVED = 'WORKFLOWS_RETRIEVED',
  WORKFLOW_RETRIEVED = 'WORKFLOW_RETRIEVED',

  // Workflow errors
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  WORKFLOW_NAME_REQUIRED = 'WORKFLOW_NAME_REQUIRED',
  WORKFLOW_VISA_TYPE_NOT_FOUND = 'WORKFLOW_VISA_TYPE_NOT_FOUND',
  WORKFLOW_VISA_TYPE_INVALID = 'WORKFLOW_VISA_TYPE_INVALID',
  WORKFLOW_INVALID_DATA = 'WORKFLOW_INVALID_DATA',
  WORKFLOW_CREATION_FAILED = 'WORKFLOW_CREATION_FAILED',
  WORKFLOW_UPDATE_FAILED = 'WORKFLOW_UPDATE_FAILED',
  WORKFLOW_DELETION_FAILED = 'WORKFLOW_DELETION_FAILED',
  WORKFLOW_DELETION_RESTRICTED = 'WORKFLOW_DELETION_RESTRICTED', // Has dependencies
  WORKFLOW_ACCESS_DENIED = 'WORKFLOW_ACCESS_DENIED',
}

// ============================================
// WORKFLOW STEP OPERATION CODES
// ============================================

export enum WorkflowStepOperationCode {
  // Success codes
  STEP_CREATED = 'STEP_CREATED',
  STEP_UPDATED = 'STEP_UPDATED',
  STEP_DELETED = 'STEP_DELETED',
  STEPS_RETRIEVED = 'STEPS_RETRIEVED',
  STEP_RETRIEVED = 'STEP_RETRIEVED',
  STEPS_REORDERED = 'STEPS_REORDERED',

  // Error codes
  STEP_NOT_FOUND = 'STEP_NOT_FOUND',
  STEP_INVALID_ORDER = 'STEP_INVALID_ORDER',
  STEP_ORDER_CONFLICT = 'STEP_ORDER_CONFLICT', // Duplicate order
  STEP_ORDER_MISSING = 'STEP_ORDER_MISSING',
  STEP_ORDER_GAP = 'STEP_ORDER_GAP', // Non-sequential orders
  STEP_NAME_REQUIRED = 'STEP_NAME_REQUIRED',
  STEP_CREATION_FAILED = 'STEP_CREATION_FAILED',
  STEP_UPDATE_FAILED = 'STEP_UPDATE_FAILED',
  STEP_DELETION_FAILED = 'STEP_DELETION_FAILED',
  STEP_MINIMUM_REQUIRED = 'STEP_MINIMUM_REQUIRED', // At least 1 step required
  STEP_INVALID_DATA = 'STEP_INVALID_DATA',
  STEP_CIRCULAR_DEPENDENCY = 'STEP_CIRCULAR_DEPENDENCY',
  STEP_REORDER_FAILED = 'STEP_REORDER_FAILED',
}

// ============================================
// WORKFLOW VERSIONING OPERATION CODES
// ============================================

export enum WorkflowVersionOperationCode {
  // Success codes
  VERSION_CREATED = 'VERSION_CREATED',
  VERSION_ACTIVATED = 'VERSION_ACTIVATED',
  VERSION_DEPRECATED = 'VERSION_DEPRECATED',
  VERSION_DELETED = 'VERSION_DELETED',
  VERSIONS_RETRIEVED = 'VERSIONS_RETRIEVED',
  VERSION_RETRIEVED = 'VERSION_RETRIEVED',
  VERSION_HISTORY_RETRIEVED = 'VERSION_HISTORY_RETRIEVED',
  STEP_MAPPINGS_DEFINED = 'STEP_MAPPINGS_DEFINED',
  STEP_MAPPINGS_RETRIEVED = 'STEP_MAPPINGS_RETRIEVED',
  ANALYTICS_RETRIEVED = 'ANALYTICS_RETRIEVED',

  // Error codes
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',
  VERSION_INVALID_STATUS = 'VERSION_INVALID_STATUS',
  VERSION_ALREADY_ACTIVE = 'VERSION_ALREADY_ACTIVE',
  VERSION_CREATION_FAILED = 'VERSION_CREATION_FAILED',
  VERSION_ACTIVATION_FAILED = 'VERSION_ACTIVATION_FAILED',
  VERSION_DEPRECATION_FAILED = 'VERSION_DEPRECATION_FAILED',
  VERSION_STEPS_INVALID = 'VERSION_STEPS_INVALID',
  VERSION_STEPS_EMPTY = 'VERSION_STEPS_EMPTY',
  VERSION_STEP_ORDER_SEQUENTIAL = 'VERSION_STEP_ORDER_SEQUENTIAL',
  VERSION_STEP_DUPLICATE = 'VERSION_STEP_DUPLICATE',
  VERSION_INCOMPATIBLE_TRANSITION = 'VERSION_INCOMPATIBLE_TRANSITION',
  VERSION_MISSING_REQUIRED_MAPPING = 'VERSION_MISSING_REQUIRED_MAPPING',
}

// ============================================
// WORKFLOW MIGRATION OPERATION CODES
// ============================================

export enum WorkflowMigrationOperationCode {
  // Success codes
  MIGRATION_STARTED = 'MIGRATION_STARTED',
  MIGRATION_COMPLETED = 'MIGRATION_COMPLETED',
  MIGRATION_FORCED = 'MIGRATION_FORCED',
  MIGRATION_SUCCESSFUL = 'MIGRATION_SUCCESSFUL',
  MIGRATIONS_RETRIEVED = 'MIGRATIONS_RETRIEVED',
  MIGRATION_RETRIEVED = 'MIGRATION_RETRIEVED',
  MIGRATION_PROGRESS_RETRIEVED = 'MIGRATION_PROGRESS_RETRIEVED',
  MIGRATION_HISTORY_RETRIEVED = 'MIGRATION_HISTORY_RETRIEVED',
  MIGRATION_VALIDATED = 'MIGRATION_VALIDATED',

  // Error codes
  MIGRATION_NOT_FOUND = 'MIGRATION_NOT_FOUND',
  MIGRATION_FAILED = 'MIGRATION_FAILED',
  MIGRATION_INVALID_SOURCE = 'MIGRATION_INVALID_SOURCE',
  MIGRATION_INVALID_TARGET = 'MIGRATION_INVALID_TARGET',
  MIGRATION_INVALID_STRATEGY = 'MIGRATION_INVALID_STRATEGY',
  MIGRATION_APPLICATION_NOT_FOUND = 'MIGRATION_APPLICATION_NOT_FOUND',
  MIGRATION_APPLICATION_COMPLETED = 'MIGRATION_APPLICATION_COMPLETED',
  MIGRATION_STEP_MAPPING_FAILED = 'MIGRATION_STEP_MAPPING_FAILED',
  MIGRATION_STEP_UNMAPPABLE = 'MIGRATION_STEP_UNMAPPABLE',
  MIGRATION_INVALID_TARGET_STEP = 'MIGRATION_INVALID_TARGET_STEP',
  MIGRATION_STRATEGY_REMAP_MISSING_TARGET = 'MIGRATION_STRATEGY_REMAP_MISSING_TARGET',
  MIGRATION_BULK_PARTIAL_FAILURE = 'MIGRATION_BULK_PARTIAL_FAILURE',
  MIGRATION_VALIDATION_FAILED = 'MIGRATION_VALIDATION_FAILED',
  MIGRATION_INCOMPATIBLE_VERSIONS = 'MIGRATION_INCOMPATIBLE_VERSIONS',
  MIGRATION_ROLLBACK_FAILED = 'MIGRATION_ROLLBACK_FAILED',
}

// ============================================
// ERROR TYPES
// ============================================

export enum WorkflowErrorType {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  OPERATION_FAILED = 'OPERATION_FAILED',
  STATE_TRANSITION_INVALID = 'STATE_TRANSITION_INVALID',
  DEPENDENCY_ERROR = 'DEPENDENCY_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
}

// ============================================
// OPERATION STATUS CODES
// ============================================

export enum OperationStatus {
  // Informational
  INFO = 'INFO',

  // Success
  SUCCESS = 'SUCCESS',

  // Partial success
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',

  // Client errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',

  // Server errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}

// ============================================
// MIGRATION STRATEGY TYPES
// ============================================

export enum MigrationStrategy {
  KEEP_CURRENT_STEP = 'KEEP_CURRENT_STEP', // Keep app at equivalent step order
  REMAP_STEP = 'REMAP_STEP', // Explicitly map to target step
  FORCED_UPDATE = 'FORCED_UPDATE', // Force to first step of new version
  MANUAL = 'MANUAL', // Manual migration path
}

// ============================================
// WORKFLOW STATUS
// ============================================

export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  DEPRECATED = 'DEPRECATED',
}
